TestOnlyPipeline(
	agent: [
		containers: [
			[name: 'golang', image: 'golang:1.25', ttyEnabled: true, command: 'cat', alwaysPullImage: true]
		],
		env       : [
			'AWS_ACCESS_KEY_ID'    : '1',
			'AWS_SECRET_ACCESS_KEY': '1',
		]
	],
	test: [
		stages: [
			[
				name : 'Prepare test environment',
				steps: {
					container('golang') {
						sh "git config --global --add safe.directory \"\$(pwd)\""
						sh 'go mod download'
					}
				}
			],
			[
				name : 'Run Tests',
				steps: {
					container('golang') {
						sh 'make build'
						sh 'make test'
						sh 'make cover'
					}
				}
			]
		]
	],
	notifications: [slack: "#bolt-dev"],
	post: {
		archiveArtifacts artifacts: 'coverage/*', followSymlinks: false, allowEmptyArchive: true
	}
)